CREATE TABLE posts (
postsid SERIAL PRIMARY KEY,
title VARCHAR(200) NOT NULL,
body TEXT NOT NULL,
date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
is_published BOOLEAN DEFAULT FALSE
);

SELECT postsid, title FROM posts

CREATE TABLE comments (
commentsid SERIAL PRIMARY KEY,
body TEXT NOT NULL,
postsid INTEGER REFERENCES posts(postsid),
date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT title,body,date_created,date_updated FROM posts